### ISSUE TITLE
WeChat Pay receive internal error

### ISSUE THREAD

**Issue by YunyyYY** [adyen-examples/adyen-react-online-payments#1]
I added WeChat Pay in my payment methods, and when I tried to check out with it I got HTTP 500 error, which said it's an "internal error". I got a similar result using `curl` (using the command specified on this [page](https://docs.adyen.com/payment-methods/wechat-pay/wechat-pay-desktop-qr-payments/web-drop-in#wechat-payments)):
```sh
{
  "status": 500,
  "errorCode": "903",
  "message": "Internal error",
  "errorType": "internal"
}
```
Is there anything I missed?

**Comment by deepu105** [comment]
Hi @YunyyYY thanks for the report. We will get back to you with suggestions. In the meantime can you check if you have WeChat pay enable in the customer area and it is returned in your paymentMethods API call?

**Comment by deepu105** [comment]
Hi @YunyyYY, also for WeChat Pay you actually can't do a sandbox/test environment, since an acquirer needs to be set. I assume you were using the test account here?

**Comment by bryancresswell** [comment]
Hey @YunyyYY, could you drop an e-mail to support@adyen.com with your merchant account code? This is due to an acquirer configuration issue on your merchant account.

**Comment by YunyyYY** [comment]
> Hi @YunyyYY, also for WeChat Pay you actually can't do a sandbox/test environment, since an acquirer needs to be set. I assume you were using the test account here?

I see! And yes, I am using a test account.

**Comment by YunyyYY** [comment]
> Hey @YunyyYY, could you drop an e-mail to [support@adyen.com](mailto:support@adyen.com) with your merchant account code? This is due to an acquirer configuration issue on your merchant account.

Thanks! I have just sent the email.

**Comment by deepu105** [comment]
@YunyyYY I hope support can fix the configuration issue for you. Let us know if you are able to get it working, else we will try to help you further

**Comment by YunyyYY** [comment]
> @YunyyYY I hope support can fix the configuration issue for you. Let us know if you are able to get it working, else we will try to help you further

Hi, yes they fixed it. Thanks a lot!
