### ISSUE TITLE
Smart buttons (PayPal and Google Pay) are not loading

### ISSUE THREAD

**Issue by sghata** [adyen-examples/adyen-react-online-payments#12]
I'm implementing a react storefront that utilizes @adyen/adyen-web.
I faced few issues during the implementation:
1. import '@adyen/adyen-web/dist/adyen.css' wasn't compiling which I got resolved by adding style-loader and css-loader to webpack config file
2. Another issue which is blocking me is smart buttons not showing and I'm not seeing any clues on why they won't.
![image](https://user-images.githubusercontent.com/19668725/143950706-d0bcd9a2-ab26-434b-bd90-882d4fe7d3b3.png)
![image](https://user-images.githubusercontent.com/19668725/143950737-ceca6771-108b-4419-8f27-8a5a3864b23d.png)
![image](https://user-images.githubusercontent.com/19668725/143950754-bb013d08-07ed-43e7-8ff2-000930b485b8.png)

A. I checked for console errors
B. I tried multiple @adyen/adyen-web versions between 5.2.0 and 5.3.1, no luck
C. Read through the updated 5.x.x documentation 20 times :)
D. Built and deployed your repository and everything seems to work. My guess it's a webpack issue.
I would really appreciate it if someone can point me in the right direction and if I'm missing something obvious

Deployed storefront (with the issue described above):
https://xcpwaretail-development.mobify-storefront.com/

**Comment by jlengrand** [comment]
Hey there, I'll have a look. Thanks for reporting.

@marcperez FYI

**Comment by sghata** [comment]
@jlengrand thank you for looking into this. Please see update below:
1. Google pay smart button is now showing. Turned out showPayButton attribute which I sat true for cards, also applied for the rest of the methods. Applying the property on the method's level fixed the issue:
`paymentMethodsConfiguration: {
                        card: {
                            showPayButton: false
                        },
                        paywithgoogle: {
                            showPayButton: true
                        },
                        paypal: {
                            showPayButton: true
                        }
                    }
`
2. PayPal smart button is giving me another issue:
![image](https://user-images.githubusercontent.com/19668725/144645207-404c2bf0-c9f3-47a7-8c36-646702756acf.png)
![image](https://user-images.githubusercontent.com/19668725/144645253-96c8236c-0f40-4f77-bf57-515750de64a9.png)
![image](https://user-images.githubusercontent.com/19668725/144645314-b98858cc-3dec-4d6f-a7d7-7204eacb6835.png)

**Comment by ribeiroguilherme** [comment]
Hi @sghata ,

I tried to access the checkout in your storefront but it isn't loading. Here are my thoughts about the problem:

I believe that the problem here is that there is some configuration missing on your PayPal setup. The line that is crashing is [this one](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/PayPal/components/PaypalButtons.tsx#L34) , when the code tries to get `FUNDING` from `paypalRef` object.

`paypalRef` references `paypal`  object which is added in the `window` object once PayPal SDK is initialized. If the object isn't there ( `window.paypal === undefined ` ), that likely means that SDK failed to load.

Can you double check your PayPal configuration on PayPal account and also on Adyen Customer Area? [Here](https://docs.adyen.com/payment-methods/paypal/web-drop-in) is the documentation for it. Also check if the PayPal script is added to the DOM at the bottom of your page, it should show up there once the payment method is opened.

**Comment by ribeiroguilherme** [comment]
About the first issue related to `showPayButton`, I tested locally and I didn't manage to reproduce the problem as you described. The pay button of my card component disappeared, but all other payment methods kept the button.

**Comment by vinodshettyhn** [comment]
Hi @ribeiroguilherme/@jlengrand, thanks for looking into this issue. 

For demo purpose, we have disabled the Paypal payment method from Adyen Dashboard. We have now activated the Paypal payment in development instance for testing as well as troubleshooting purpose and still we are unable to see the Paypal button in our storefront site.

Please find the below screenshot for reference -
<img width="936" alt="Screenshot 2022-02-03 at 12 23 37 AM" src="https://user-images.githubusercontent.com/42642738/152219594-b17cffd9-42c5-41ef-b764-a7e28cc93a48.png">

Demo Site URL - https://xcpwaretail-development.mobify-storefront.com/en-US/checkout 

I have tried to update "paypalConfiguration" object but still the button elements does not show up in Dom.

I would request to look into this issue as other payment buttons are loading properly and really appreciate if any inputs will be provided to fix it.

**Comment by vinodshettyhn** [comment]
Hi @ribeiroguilherme/@jlengrand,

Thanks for checking the issue, i am able to see the buttons and it was cased due to creation of duplicate  PP id in DOM.

Please close the ticket.

Thanks,
Vinod HN
