### ISSUE TITLE
Accessing status of components?

### ISSUE THREAD

**Issue by davidohlin** [adyen-examples/adyen-react-online-payments#126]
Hi! Sorry if this is the wrong place for questions. Feel free to close and I'll contact support.

In the docs a `status` is [mentioned](https://docs.adyen.com/online-payments/web-drop-in/optional-configuration#optional-adyen-checkout-configuration) on both components and dropin, stating:

```
setStatusAutomatically 
Set to false to not set the Drop-in status to 'loading' when onSubmit is triggered. Defaults to true.
```

However, I can't find a `status` property anywhere on a component instance. Is that a typo in the docs, or is it possible to get the current status of a component?

Thanks!

**Comment by jlengrand** [comment]
Hey there! 

Hum, as far as I can see it should be there in both? 

I can see the `setStatusAutomatically` being checked [in the UIElement class](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/UIElement.tsx#L56), which all components (including Dropin) extend from.

Example [here for Paypal](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/PayPal/Paypal.tsx#L12).

What do you mean exacting by finding anywhere? Are you trying to access it in the react component itself?

**Comment by gcatanese** [comment]
Closing as there is a response and no further activity
