### ISSUE TITLE
Not working redirection when using different payment method after making successful payment first time

### ISSUE THREAD

**Issue by pborzecki** [adyen-examples/adyen-react-online-payments#20]
I noticed problem with not working redirection when using different payment method after making successful payment first time.

To reproduce problem I perform following scenario:
1. Use drop-in 
2. Pay with test card 
3. After successful payment processing return home
4. Use drop-in one more time
5. Choose iDEAL method
6. Select test bank (i.e. Test Issuer 5)
7. Click Continue... button
8. Redirection didn't occur. Button is still clickable.
9. Reload page
10. Choose iDEAL method
11. Select test bank
12. Click Continue... button
13. Redirection occurred properly

In this screen cast you can find how test scenario looks:
https://user-images.githubusercontent.com/578223/161933153-053f6634-bde0-4e21-8faf-57d2b9a84762.mp4

I tested with @adyen/web and @adyen/api-library libraries in the same versions as in demo and after updating them to the newest versions (@adyen/adyen-web 5.12.0 and @adyen/api-library 10.2.0). In both cases the problem is still present.

I'm not sure if described problem relates to usage of @adyen/web library in this demo or to library itself, so I firstly reported problem here.

**Comment by pborzecki** [comment]
I found out that the problem is relates to state which keeps old session object when creating  AdyenCheckout object. So I applied workaround with clearing state before requesting another payment (PR #21)  and it looks like it works for me and cause that problem does not occur.

**Comment by gcatanese** [comment]
Many thanks @pborzecki
