### ISSUE TITLE
The payment was refused. Please try a different payment method or card.

### ISSUE THREAD

**Issue by MishaVernik** [adyen-examples/adyen-react-online-payments#23]
Hey guys!

I've tried .net and react versions, and in both cases I get:

![image](https://user-images.githubusercontent.com/41151124/163836723-6d9c8e27-6c18-4adc-b030-1dfed721466f.png)

I suggest the problem lies with ENV keys, in case REACT_APP_ADYEN_CLIENT_KEY. 

Could you please provide an example of the correct setup?

Kind regards,
Misha

**Comment by MishaVernik** [comment]
Hi @gcatanese, sure.

Steps:
1. Created a Test account at Adyen
2.  Generated ws -> API Key
3. Deployed to heroku.com asp.net / react (see the image below) and added the REACT_APP_ADYEN_CLIENT_KEY
4. I sent some transactions (the first 3 are the test transactions, after them VISA & MASTERCARD)
5. I picked Drop-in & Credit Card options on the website and after writing Test Credit Cards data I got this image (image from the issue)
6. I Tried to setup a "Standard notification" webhook but it didn't go well.

![image](https://user-images.githubusercontent.com/41151124/164060857-ce42f9d1-5472-47b3-b721-fa5c7249d0bb.png)
![image](https://user-images.githubusercontent.com/41151124/164061223-1c26fc76-67a2-40e7-abbb-faed75b8428f.png)

**Comment by gcatanese** [comment]
The setup is correct, but payments with a score of 100+ are refused. I have reached to our teams internally to understand which options we have to lower the score. Can you try another form of payment meanwhile?

**Comment by MishaVernik** [comment]
Hi @gcatanese,

1. I tried non-card payments (image below), and some of them showed the "Success" screen.
2. Tried my VISA card (Risk score = 30) and PL Mastercard & Visa cards too, but still get the second image.

Any ideas?

![image](https://user-images.githubusercontent.com/41151124/164413229-18ab1ba7-8b4a-4827-a70a-a9613a86b960.png)


![image](https://user-images.githubusercontent.com/41151124/164413113-9c11685b-c15e-4b77-aa9a-3838330ba083.png)

![image](https://user-images.githubusercontent.com/41151124/164414355-711059bd-c920-4935-904f-d88a33191912.png)

**Comment by gcatanese** [comment]
Hi @MishaVernik, sorry, it took some time to dive into the risk rules and profiles.

The payment with a score of `30` is refused because of this reason: `[Refused (DECLINED Expiry Incorrect)]`

The other card payments (including Pay by Link) always produce a score higher than 100 because of multiple rules: I am going to reach out to Support to lower your Risk Profile (on TEST those rules shouldn't be enabled - for some reasons they are on your test account). Non-card payments should work - apologies for the inconvenience and I will let you know when this is sorted.

**Comment by MishaVernik** [comment]
Morning @gcatanese,

Just double-checked Expiry Date & CVV2, "The payment with a score of 30 is refused because of this reason: [Refused (DECLINED Expiry Incorrect)]" and I get 0 Risk Score, but still got it refused. I hope that's because support is doing smth with it.  

![image](https://user-images.githubusercontent.com/41151124/164686228-0f1aa562-4d74-4a95-9b07-dddc517ef070.png)

**Comment by gcatanese** [comment]
@MishaVernik I see now a total risk score of 0 so probably Support has reset your risk profile (I haven't heard confirmation yet).
Can you try one of the Adyen [test cards](https://docs.adyen.com/development-resources/testing/test-card-numbers
) please?

The last payment fails for a different reason: the error says invalid expiry date (which is not the case - I see `12/2024`), I also see `Supplied, Issuer not certified for CVC/CVV (U)`, does the card have a CVC? Do you pass one anyway? 
Try maybe a payment without setting the CVC. If it doesn't work it must be a specific problem with that card, in this case it is best to log a ticket directly with Adyen Support so they can investigate for you.

**Comment by MishaVernik** [comment]
@gcatanese, please take a look.

1. Tried Adyen test cards
2. Maybe I have to resetup everything from the beginning?
3. "I also see Supplied, Issuer not certified for CVC/CVV (U)" - yes, I have a dynamic CVV (every 60 minutes it updates).

![image](https://user-images.githubusercontent.com/41151124/164724884-95e7fabf-6d93-404d-9181-79acd8b3bfcb.png)

![image](https://user-images.githubusercontent.com/41151124/164724936-7e20588e-c6ce-4444-9dab-9808a0b19ec9.png)

![image](https://user-images.githubusercontent.com/41151124/164724971-710f3850-a167-403e-8671-0bf4394314df.png)

![image](https://user-images.githubusercontent.com/41151124/164725293-471c2ff7-bed4-42fa-b355-fe6806daacb2.png)

![image](https://user-images.githubusercontent.com/41151124/164725316-7a721cbb-6687-4ae5-8e61-b40a4247b86d.png)

**Comment by gcatanese** [comment]
@MishaVernik It looks like your risk score is still too high, I have followed up with Support and hopefully they will correct it soon. Next week I am not around but I will ask a team member to work on this so it can finally sorted out for you.

It is best to remove all screenshots showing keys and secrets (from previous comments).

**Comment by MishaVernik** [comment]
Hey guys, any updates on it?

**Comment by jlengrand** [comment]
Hey @MishaVernik. @gcatanese is on holidays and yesterday was a national holiday.

I see you have had issues with risk profiles. Are test cards provided by Adyen still failing for you? In that case, can you check the payload of the response that you get at the refusal (In developers -> API Logs).

You should have had your risk profile reset in any case.  Any risk score over 100 will be refused.

**Comment by Minneth** [comment]
We are getting the exact same issue. We're using the Drop-In component and all test card payments are being either refused or cancelled. We've even tested using the example provided in this github and get the same result.

Do we have an update on this issue please?

**Comment by gcatanese** [comment]
hi @Minneth, can you provide me the PSPReference please?

**Comment by Minneth** [comment]
Hi @gcatanese, I certainly can provide a few actually:

ZW24RC4SQ5PFWR82
S84N49LNZ5ZW8N82
BZ269Z63VSGLNK82

Thanks in advance.

**Comment by gcatanese** [comment]
@alizenguyen @Minneth I raised the issue with the Adyen Test Cards and the team is looking into it (possibly adding them into the Allowed list). The other factor affecting the score is the number of different attempts with different cards in the last X days: this is expected on `live`, but I understand it is inconvenient on `test`.

There are 2 workarounds:

### Skip risk rules
During your development/testing you can instruct the platform to skip risk checks (https://docs.adyen.com/risk-management/skip-risk-rules), by adding `riskdata.skipRisk` as additionalData of the payment request, for example when you initiate the `session`

```
amount: { 
   currency: "EUR", 
   value: 1000
},
merchantAccount: "xyz",
reference: "abc",
additionalData: {
   "riskdata.skipRisk": true
}
```
The transaction will always have a Risk Score equals to 0.

### Disable Risk Profile
Access the Risk Settings (if you are a Risk Admin) and turn off completely the Risk system (https://docs.adyen.com/risk-management/configure-risk-settings)

**Comment by gcatanese** [comment]
@alizenguyen @Minneth Did any of the suggested approaches work for you? Let me know if there is still something we can do/help with.

**Comment by alizenguyen** [comment]
@gcatanese Yes I was able to get it resolved, thank you!
