### ISSUE TITLE
3DS native flow does not work

### ISSUE THREAD

**Issue by ioanlucut** [adyen-examples/adyen-react-online-payments#3]
Thank you for this repo and the examples you provided.

However, while trying to implement and test the solution, I noticed that testing the 3DS 2 Native Flow does not work.
I tried to use it by https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication card `4212 3456 7891 0006` VISA test card.

What happens instead, the UI gets frozen after the password is submitted to the 3DS mock view.
Will you be so nice to have a look? Thank you.

**Comment by lukovskij** [comment]
had the same issue :)
try to change hardcoded returnUrl and hardcoded origin to your current values (http://localhost:3000)

**Comment by ioanlucut** [comment]
@lukovskij thank you! That one indeed fixed the issue. I opened a PR: https://github.com/adyen-examples/adyen-react-online-payments/pull/4

**Comment by deepu105** [comment]
Hi it depends on how you run the examples. If you follow the readme and run just `npm run server` the server runs on `localhost:8080` and the code works fine. But if you run server and client seperately with `npm run server-dev` and `npm start` then indeed you need to change the URL to `localhost:3000`. I'll document this
