### ISSUE TITLE
Updated example for 5.0.0?

### ISSUE THREAD

**Issue by tmadison-gpsw** [adyen-examples/adyen-react-online-payments#7]
I see the payment session has been reduced to one API call (https://docs.adyen.com/online-payments/web-drop-in?tab=codeBlocksessions_1) to the server can you provide an updated example of this with Node/Express/React? 

Thanks!

**Comment by jlengrand** [comment]
Hey @tmadison-gpsw . Indeed, this was needed. 

I just merged https://github.com/adyen-examples/adyen-react-online-payments/pull/8, which is now using the /sessions endpoint. 

Let me know if you face issues
